<a href="https://colab.research.google.com/github/135Parthasarathi/singlePageApp/blob/main/StudentMarksPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
rng = np.random.default_rng()

In [ ]:
attendence = rng.integers(0,101,size=(64))
print(attendence)

[38 14 92 44 51 27  0 12 16 46 16 88 35 96 29 92 21 60 90 65  0 92 78 13
 38 60 79 46 89 30 87 84 57 87 47 12 29 19 46 25 37 23 34 33 20 95 65 36
 13 75 32 64 11 28 32 65 48 11 25 63 50  3 96 92]


In [ ]:
studyhours = rng.integers(0,11,size=(64))
print(studyhours)

[ 9  9  8 10  0  4 10 10  0  8  8  1  8 10 10  3  4  7  5 10  7  4  8 10
  1  8  6  9  5  0  5  1  5  6  6  3  7  6  8  7  6  7  8  9  8  9  6 10
 10  0  1  1  9  4  7  5 10  2 10  2  0  9  4  4]


In [ ]:
dataset=np.vstack((attendence,studyhours))
print(dataset)

[[38 14 92 44 51 27  0 12 16 46 16 88 35 96 29 92 21 60 90 65  0 92 78 13
  38 60 79 46 89 30 87 84 57 87 47 12 29 19 46 25 37 23 34 33 20 95 65 36
  13 75 32 64 11 28 32 65 48 11 25 63 50  3 96 92]
 [ 9  9  8 10  0  4 10 10  0  8  8  1  8 10 10  3  4  7  5 10  7  4  8 10
   1  8  6  9  5  0  5  1  5  6  6  3  7  6  8  7  6  7  8  9  8  9  6 10
  10  0  1  1  9  4  7  5 10  2 10  2  0  9  4  4]]


In [ ]:
dataset=dataset.T
print(dataset)

[[38  9]
 [14  9]
 [92  8]
 [44 10]
 [51  0]
 [27  4]
 [ 0 10]
 [12 10]
 [16  0]
 [46  8]
 [16  8]
 [88  1]
 [35  8]
 [96 10]
 [29 10]
 [92  3]
 [21  4]
 [60  7]
 [90  5]
 [65 10]
 [ 0  7]
 [92  4]
 [78  8]
 [13 10]
 [38  1]
 [60  8]
 [79  6]
 [46  9]
 [89  5]
 [30  0]
 [87  5]
 [84  1]
 [57  5]
 [87  6]
 [47  6]
 [12  3]
 [29  7]
 [19  6]
 [46  8]
 [25  7]
 [37  6]
 [23  7]
 [34  8]
 [33  9]
 [20  8]
 [95  9]
 [65  6]
 [36 10]
 [13 10]
 [75  0]
 [32  1]
 [64  1]
 [11  9]
 [28  4]
 [32  7]
 [65  5]
 [48 10]
 [11  2]
 [25 10]
 [63  2]
 [50  0]
 [ 3  9]
 [96  4]
 [92  4]]


In [ ]:
w1=0.4
w2=5
bias=8

In [ ]:
marks=(w1*attendence+w2*studyhours)+bias
print(marks)

[68.2 58.6 84.8 75.6 28.4 38.8 58.  62.8 14.4 66.4 54.4 48.2 62.  96.4
 69.6 59.8 36.4 67.  69.  84.  43.  64.8 79.2 63.2 28.2 72.  69.6 71.4
 68.6 20.  67.8 46.6 55.8 72.8 56.8 27.8 54.6 45.6 66.4 53.  52.8 52.2
 61.6 66.2 56.  91.  64.  72.4 63.2 38.  25.8 38.6 57.4 39.2 55.8 59.
 77.2 22.4 68.  43.2 28.  54.2 66.4 64.8]


In [ ]:
dataset = np.hstack((dataset,np.ones((64,1))))
print(dataset)

[[38.  9.  1.]
 [14.  9.  1.]
 [92.  8.  1.]
 [44. 10.  1.]
 [51.  0.  1.]
 [27.  4.  1.]
 [ 0. 10.  1.]
 [12. 10.  1.]
 [16.  0.  1.]
 [46.  8.  1.]
 [16.  8.  1.]
 [88.  1.  1.]
 [35.  8.  1.]
 [96. 10.  1.]
 [29. 10.  1.]
 [92.  3.  1.]
 [21.  4.  1.]
 [60.  7.  1.]
 [90.  5.  1.]
 [65. 10.  1.]
 [ 0.  7.  1.]
 [92.  4.  1.]
 [78.  8.  1.]
 [13. 10.  1.]
 [38.  1.  1.]
 [60.  8.  1.]
 [79.  6.  1.]
 [46.  9.  1.]
 [89.  5.  1.]
 [30.  0.  1.]
 [87.  5.  1.]
 [84.  1.  1.]
 [57.  5.  1.]
 [87.  6.  1.]
 [47.  6.  1.]
 [12.  3.  1.]
 [29.  7.  1.]
 [19.  6.  1.]
 [46.  8.  1.]
 [25.  7.  1.]
 [37.  6.  1.]
 [23.  7.  1.]
 [34.  8.  1.]
 [33.  9.  1.]
 [20.  8.  1.]
 [95.  9.  1.]
 [65.  6.  1.]
 [36. 10.  1.]
 [13. 10.  1.]
 [75.  0.  1.]
 [32.  1.  1.]
 [64.  1.  1.]
 [11.  9.  1.]
 [28.  4.  1.]
 [32.  7.  1.]
 [65.  5.  1.]
 [48. 10.  1.]
 [11.  2.  1.]
 [25. 10.  1.]
 [63.  2.  1.]
 [50.  0.  1.]
 [ 3.  9.  1.]
 [96.  4.  1.]
 [92.  4.  1.]]


In [ ]:
w=np.linalg.inv(dataset.T @ dataset)@dataset.T@marks
print(w)

[0.4 5.  8. ]


In [ ]:
data = np.vstack((attendence,studyhours,marks)).T
print(data)

[[38.   9.  68.2]
 [14.   9.  58.6]
 [92.   8.  84.8]
 [44.  10.  75.6]
 [51.   0.  28.4]
 [27.   4.  38.8]
 [ 0.  10.  58. ]
 [12.  10.  62.8]
 [16.   0.  14.4]
 [46.   8.  66.4]
 [16.   8.  54.4]
 [88.   1.  48.2]
 [35.   8.  62. ]
 [96.  10.  96.4]
 [29.  10.  69.6]
 [92.   3.  59.8]
 [21.   4.  36.4]
 [60.   7.  67. ]
 [90.   5.  69. ]
 [65.  10.  84. ]
 [ 0.   7.  43. ]
 [92.   4.  64.8]
 [78.   8.  79.2]
 [13.  10.  63.2]
 [38.   1.  28.2]
 [60.   8.  72. ]
 [79.   6.  69.6]
 [46.   9.  71.4]
 [89.   5.  68.6]
 [30.   0.  20. ]
 [87.   5.  67.8]
 [84.   1.  46.6]
 [57.   5.  55.8]
 [87.   6.  72.8]
 [47.   6.  56.8]
 [12.   3.  27.8]
 [29.   7.  54.6]
 [19.   6.  45.6]
 [46.   8.  66.4]
 [25.   7.  53. ]
 [37.   6.  52.8]
 [23.   7.  52.2]
 [34.   8.  61.6]
 [33.   9.  66.2]
 [20.   8.  56. ]
 [95.   9.  91. ]
 [65.   6.  64. ]
 [36.  10.  72.4]
 [13.  10.  63.2]
 [75.   0.  38. ]
 [32.   1.  25.8]
 [64.   1.  38.6]
 [11.   9.  57.4]
 [28.   4.  39.2]
 [32.   7.  55.8]
 [65.   5.